import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" relative">
      <body className={inter.className}>
          <div className="bg-primary">
        <div class=" container mx-auto w-auto h-auto -z-10 overflow-x-clip bg-primary">
          <Image
            aria-hidden="true"
            src="/textura/textura-2.png"
            className=" md:scale-125 lg:scale-100 lg:left-0 top-0 opacity-25 transform-gpu  brightness-0 dark:brightness-200
          animate-fade-in animate-duration-500 z-10"
            layout="fill"
            

          
            alt="Focos de luz"
          />
          
        </div>
          {children}
          
          </div>
      </body>
    </html>
  );
}
