import { Inter } from "next/font/google";
import Image from "next/image";
import Menu from "@/components/menu";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" relative">
      <body className={inter.className}>
        <div className="bg-primary">
        <Menu />
          <div class=" container  w-auto h-auto z-0  bg-primary">
            <Image
              aria-hidden="true"
              src="/textura/textura-2.png"
              className="   top-0 opacity-25  z-10 "
              layout="fill"
              alt="Focos de luz"
            />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
